name: Publish Canary Packages

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: 'Publish Canary Packages'
    environment: npm deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest-16-cores-open

    steps:
      - name: tldraw-repo-sync token
        id: tldraw-repo-sync
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.HUPPY_APP_ID }}
          private_key: ${{ secrets.HUPPY_APP_PRIVATE_KEY }}

      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: 'public-yarn.lock'

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Publish Canary Packages
        run: yarn tsx ./scripts/publish-canary.ts
        env:
          GH_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
